---
title: "mds"
output: pdf_document
date: "2025-02-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(cluster)
library(MASS)
library(kmed)
library(lsa)
library(nomclust)
library(UBL)
library(stats)
library(datasets)
library(manydist)
library(ggplot2)
library(FactoMineR)
library(tidyverse)
library(Rtsne)
library(plotly)
set.seed(2025)
```

```{r files}
source('../Simulation Study/classes.R')
source('../Simulation Study/sim_study_funcs.R')
```


```{r breast cancer data preprocess, echo=T, results='hide'}
breast_data <- read.csv('../data/breast-cancer.csv')
breast_df <- breast_data[,-c(1:2)]
breast_clus <- breast_data[,2]
```

```{r breast cancer data cluster, echo=T, results='hide'}
ubdep_dist_breast <- mdist(breast_df)
eucl_dist_breast <- dist(breast_df, method="euclidean")
gower_dist_breast <- daisy(breast_df, metric="gower")
cos_dist_breast <- 1 - cosine(t(breast_df))
HVDM_dist_breast <- distances(1, breast_df, 'HVDM')
```

```{r isomds breast, echo=T, results='hide'}
ubdep_mds_breast <- isoMDS(ubdep_dist_breast)$points
eucl_mds_breast <- isoMDS(eucl_dist_breast)$points
gower_mds_breast <- isoMDS(gower_dist_breast)$points
cos_mds_breast <- isoMDS(cos_dist_breast)$points
HVDM_mds_breast <- isoMDS(HVDM_dist_breast)$points
```

```{r breast data MDS, fig.dim = c(8, 4)}
ggplot(data.frame(ubdep_mds_breast), aes(x = X1, y = X2)) + geom_point() + ggtitle('UBDep MDS: Breast Data')
ggplot(data.frame(eucl_mds_breast), aes(x = X1, y = X2)) + geom_point() + ggtitle('Eucl MDS: Breast Data')
ggplot(data.frame(gower_mds_breast), aes(x = X1, y = X2)) + geom_point() + ggtitle('Gower MDS: Breast Data')
ggplot(data.frame(cos_mds_breast), aes(x = X1, y = X2)) + geom_point() + ggtitle('Cos MDS: Breast Data')
ggplot(data.frame(HVDM_mds_breast), aes(x = X1, y = X2)) + geom_point() + ggtitle('HVDM MDS: Breast Data')

```

```{r mds plots breast}
g_ub_mds_breast <- ggplot(data.frame(ubdep_mds_breast), aes(x = X1, y = X2)) + geom_point(size=0.1) + ggtitle('Unbiased Dependent') + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
g_eucl_mds_breast <- ggplot(data.frame(eucl_mds_breast), aes(x = X1, y = X2)) + geom_point(size=0.1) + ggtitle('Euclidean') + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
g_gower_mds_breast <- ggplot(data.frame(gower_mds_breast), aes(x = X1, y = X2)) + geom_point(size=0.1) + ggtitle('Gower') + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
g_cos_mds_breast <- ggplot(data.frame(cos_mds_breast), aes(x = X1, y = X2)) + geom_point(size=0.1) + ggtitle('Cosine') + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
g_HVDM_mds_breast <- ggplot(data.frame(HVDM_mds_breast), aes(x = X1, y = X2)) + geom_point(size=0.1) + ggtitle('HVDM') + theme(axis.title.x=element_blank(), axis.title.y=element_blank())

title = cowplot::ggdraw() + cowplot::draw_label('MDS: Breast Cancer', color = "black", fontface = "bold", size = 16)
top_row = cowplot::plot_grid(g_ub_mds_breast, g_eucl_mds_breast, g_gower_mds_breast, g_cos_mds_breast, ncol=2, nrow=2)
bottom_row = cowplot::plot_grid(NULL, g_HVDM_mds_breast, NULL, ncol=3, rel_widths=c(0.25,0.5,0.25))

cowplot::plot_grid(title, top_row, bottom_row, ncol=1, rel_heights=c(0.1,1,0.5))
ggsave("mds_breast.png", width = 6, height = 8) 
```


```{r customer segmentation data preprocess, echo=T, results='hide'}
set.seed(2025)
cust_data <- read.csv('../data/customer_segmentation.csv', sep=",")
cust_data <- na.omit(cust_data)

cust_data <- cust_data[-c(which(cust_data$Ever_Married == "")),]
cust_data <- cust_data[-c(which(cust_data$Graduated == "")),]
cust_data <- cust_data[-c(which(cust_data$Profession == "")),]
cust_data <- cust_data[-c(which(cust_data$Var_1 == "")),]

rand_cust = sample(nrow(cust_data), nrow(cust_data)%/%10)
cust_df <- cust_data[,-c(1,11)][rand_cust,]
cust_clus <- cust_data[,11][rand_cust]

cust_clus <- cust_clus[!duplicated(cust_df)]
cust_df <- cust_df[!duplicated(cust_df),]

for (x in c(1:2,4:5,7,9)) {
   cust_df[,x] <- factor(cust_df[,x])
}

cust_num_df = cust_df
for (x in c(1:ncol(cust_num_df))){
  cust_num_df[,x] <- as.numeric(cust_num_df[,x])
}
```

```{r customer segmentation data cluster, echo=T, results='hide'}
ubdep_dist_cust <- mdist(cust_df)
eucl_dist_cust <- dist(cust_num_df, method="euclidean")
gower_dist_cust <- daisy(cust_df, metric="gower", 
                          type=list(asymm=c(1:2,4), factor=c(5,7,9)))
cos_dist_cust <- 1 - cosine(t(cust_num_df))
HVDM_dist_cust <- distances(1, cust_df, 'HVDM')
ahm_dist_cust <- distmix(cust_df, method = 'ahmad', 
                         idnum=c(3,6,8), idbin=c(1:2,4), idcat=c(5,7,9))
```

```{r isomds cust, echo=T, results='hide'}
ubdep_mds_cust <- isoMDS(ubdep_dist_cust)$points
eucl_mds_cust <- isoMDS(eucl_dist_cust)$points
gower_mds_cust <- isoMDS(gower_dist_cust)$points
cos_mds_cust <- isoMDS(cos_dist_cust)$points
HVDM_mds_cust <- isoMDS(HVDM_dist_cust + 0.001)$points
ahm_mds_cust <- isoMDS(ahm_dist_cust)$points
```

```{r mds plots cust}
g_ub_mds_cust <- ggplot(data.frame(ubdep_mds_cust), aes(x = X1, y = X2)) + geom_point(size=0.1) + ggtitle('Unbiased Dependent') + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
g_eucl_mds_cust <- ggplot(data.frame(eucl_mds_cust), aes(x = X1, y = X2)) + geom_point(size=0.1) + ggtitle('Euclidean') + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
g_gower_mds_cust <- ggplot(data.frame(gower_mds_cust), aes(x = X1, y = X2)) + geom_point(size=0.1) + ggtitle('Gower') + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
g_cos_mds_cust <- ggplot(data.frame(cos_mds_cust), aes(x = X1, y = X2)) + geom_point(size=0.1) + ggtitle('Cosine') + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
g_HVDM_mds_cust <- ggplot(data.frame(HVDM_mds_cust), aes(x = X1, y = X2)) + geom_point(size=0.1) + ggtitle('HVDM') + theme(axis.title.x=element_blank(), axis.title.y=element_blank())
g_ahm_mds_cust <- ggplot(data.frame(ahm_mds_cust), aes(x = X1, y = X2)) + geom_point(size=0.1) + ggtitle('Ahmad & Dey') + theme(axis.title.x=element_blank(), axis.title.y=element_blank())

grid_plot <- ggarrange(g_ub_mds_cust, g_eucl_mds_cust, g_gower_mds_cust, g_cos_mds_cust, g_HVDM_mds_cust, g_ahm_mds_cust, ncol = 2, nrow = 3)
grid_plot <- annotate_figure(grid_plot,
             top = text_grob('MDS: Customer Segmentation', color = "black", face = "bold", size = 16))

print(grid_plot)
ggsave("mds.png", plot=grid_plot, width = 6, height = 8) 
```


```{r MDS customer segmentation data, fig.dim = c(8, 4)}
ggplot(data.frame(ubdep_mds_cust), aes(x = X1, y = X2)) + geom_point() + ggtitle('UBDep MDS: Customer Segmentation Data')
ggplot(data.frame(eucl_mds_cust), aes(x = X1, y = X2)) + geom_point() + ggtitle('Eucl MDS: Customer Segmentation Data')
ggplot(data.frame(gower_mds_cust), aes(x = X1, y = X2)) + geom_point() + ggtitle('Gower MDS: Customer Segmentation Data')
ggplot(data.frame(cos_mds_cust), aes(x = X1, y = X2)) + geom_point() + ggtitle('Cos MDS: Customer Segmentation Data')
ggplot(data.frame(HVDM_mds_cust), aes(x = X1, y = X2)) + geom_point() + ggtitle('HVDM MDS: Customer Segmentation Data')
ggplot(data.frame(ahm_mds_cust), aes(x = X1, y = X2)) + geom_point() + ggtitle('A&D MDS: Customer Segmentation Data')

```

```{r Gap Statistic cust data}
gap1 = clusGap(cust_num_df, pam, K.max=12, B=50)
clusters_globalSEmax <- maxSE(gap1$Tab[, "gap"], gap1$Tab[, "SE.sim"], method = "globalSEmax")
clusters_globalmax <- maxSE(gap1$Tab[, "gap"], gap1$Tab[, "SE.sim"], method = "globalmax")

print(clusters_globalSEmax)
print(clusters_globalmax)

labels_globalSEmax = pam(gower_dist_cust, clusters_globalSEmax, diss = TRUE)$clustering
labels_globalmax = pam(gower_dist_cust, clusters_globalmax, diss = TRUE)$clustering
```

```{r Gower + MDS cust data colour coded}
# Convert to data frame suitable for ggplot2
mds_SEmax <- data.frame(X1 = gower_mds_cust[,1], 
                     X2 = gower_mds_cust[,2], 
                     Label = as.factor(labels_globalSEmax))
names(mds_SEmax) <- c("Dim1", "Dim2", "Label")

# Plot and save
plot_SEmax <- ggplot(mds_SEmax, aes(x = Dim1, y = Dim2, color = Label)) + 
          geom_point() +
          labs(title='Gower MDS: Customer Segmentation') +
          scale_color_brewer(palette = "Paired") + 
          geom_point(size=0.1) + 
          theme(axis.title.x=element_blank(), axis.title.y=element_blank())
ggsave('cust_mds_SEmax.png', plot_SEmax, width = 6, height = 6)
print(plot_SEmax)

# Repeat with other labels
mds_max <- data.frame(X1 = gower_mds_cust[,1], 
                     X2 = gower_mds_cust[,2], 
                     Label = as.factor(labels_globalmax))
names(mds_max) <- c("Dim1", "Dim2", "Label")

# Plot and save
plot_max <- ggplot(mds_max, aes(x = Dim1, y = Dim2, color = Label)) + 
  geom_point() +
  labs(title='Gower MDS: Customer Segmentation') +
  scale_color_brewer(palette = "Paired") + 
  geom_point(size=0.1) + 
  theme(axis.title.x=element_blank(), axis.title.y=element_blank())
ggsave('cust_mds_max.png', plot_max, width = 6, height = 6)
print(plot_max)
```
```{r Scores on gower cust mds}
dim_tab_names = c('Clusters', 'ARI', 'AMI', 'Sil')
g_mds_evals = array(dim=c(2,4), dimnames = list(c(1:2), dim_tab_names))

dist_gower_mds_cust <- dist(gower_mds_cust, method="euclidean")

g_mds_evals[1,1] <- clusters_globalSEmax
g_mds_evals[1,2] <- ARI(cust_clus, labels_globalSEmax)
g_mds_evals[1,3] <- AMI(cust_clus, labels_globalSEmax)
g_mds_evals[1,4] <- mean(silhouette(labels_globalSEmax, dist_gower_mds_cust)[,3])

g_mds_evals[2,1] <- clusters_globalmax
g_mds_evals[2,2] <- ARI(cust_clus, labels_globalmax)
g_mds_evals[2,3] <- AMI(cust_clus, labels_globalmax)
g_mds_evals[2,4] <- mean(silhouette(labels_globalmax, dist_gower_mds_cust)[,3])

print(kable(g_mds_evals, caption = 'Clustering Statistics on MDS Projections'))
```

```{r FAMD cust data colour coded}
famd_res <- FAMD(cust_df, graph = FALSE)

# First set of labels
famd_SEmax <- data.frame(X1 = famd_res$ind$coord[,1], 
                      X2 = famd_res$ind$coord[,2], 
                      Label = as.factor(labels_globalSEmax))
names(famd_SEmax) <- c("Dim1", "Dim2", "Label")

plot_FAMD_SEmax <- ggplot(famd_SEmax, aes(x = Dim1, y = Dim2, color = Label)) +
  geom_point() +
  labs(title = "FAMD: Customer Segmentation") +
  scale_color_brewer(palette = "Paired") + 
  geom_point(size=0.1) + 
  theme(axis.title.x=element_blank(), axis.title.y=element_blank())
ggsave('cust_FAMD_SEmax.png', plot_FAMD_SEmax, width = 6, height = 6)
print(plot_FAMD_SEmax)

# Second set of labels
famd_max <- data.frame(X1 = famd_res$ind$coord[,1], 
                      X2 = famd_res$ind$coord[,2], 
                      Label = as.factor(labels_globalmax))
names(famd_max) <- c("Dim1", "Dim2", "Label")

plot_FAMD_max <- ggplot(famd_max, aes(x = Dim1, y = Dim2, color = Label)) +
  geom_point() +
  labs(title = "FAMD: Customer Segmentation") +
  scale_color_brewer(palette = "Paired") + 
  geom_point(size=0.1) + 
  theme(axis.title.x=element_blank(), axis.title.y=element_blank())
  
ggsave('cust_FAMD_max.png', plot_FAMD_max, width = 6, height = 6)
print(plot_FAMD_max)
```


```{r Scores on gower cust FAMD}
dim_tab_names = c('Clusters', 'ARI', 'AMI', 'Sil')
g_famd_evals = array(dim=c(2,4), dimnames = list(c(1:2), dim_tab_names))

dist_gower_famd_cust <- dist(famd_res$ind$coord, method="euclidean")

g_famd_evals[1,1] <- clusters_globalSEmax
g_famd_evals[1,2] <- ARI(cust_clus, labels_globalSEmax)
g_famd_evals[1,3] <- AMI(cust_clus, labels_globalSEmax)
g_famd_evals[1,4] <- mean(silhouette(labels_globalSEmax, dist_gower_famd_cust)[,3])

g_famd_evals[2,1] <- clusters_globalmax
g_famd_evals[2,2] <- ARI(cust_clus, labels_globalmax)
g_famd_evals[2,3] <- AMI(cust_clus, labels_globalmax)
g_famd_evals[2,4] <- mean(silhouette(labels_globalmax, dist_gower_famd_cust)[,3])

print(kable(g_famd_evals, caption = 'Clustering Statistics on FAMD Projections'))
```


```{r TSNE cust data color coded}
tsne_res <- Rtsne(gower_dist_cust, is_distance = TRUE)

# First set of labels
tsne_SEmax <- data.frame(X1 = tsne_res$Y[,1], 
                        X2 = tsne_res$Y[,2], 
                        Label = as.factor(labels_globalSEmax))
names(tsne_SEmax) <- c("Dim1", "Dim2", "Label")

plot_TSNE_SEmax <- ggplot(aes(x = Dim1, y = Dim2, color = Label), data = tsne_SEmax) +
  geom_point() +
  labs(title = "T-SNE: Customer Segmentation") +
  scale_color_brewer(palette = "Paired") + 
  geom_point(size=0.1) + 
  theme(axis.title.x=element_blank(), axis.title.y=element_blank())
ggsave('cust_TSNE_SEmax.png', plot_TSNE_SEmax, width = 6, height = 6)
print(plot_TSNE_SEmax)

tsne_max <- data.frame(X1 = tsne_res$Y[,1], 
                        X2 = tsne_res$Y[,2], 
                        Label = as.factor(labels_globalmax))
names(tsne_max) <- c("Dim1", "Dim2", "Label")

plot_TSNE_max <- ggplot(aes(x = Dim1, y = Dim2, color= Label), data = tsne_max) +
  geom_point() +
  labs(title = "T-SNE: Customer Segmentation") +
  scale_color_brewer(palette = "Paired") + 
  geom_point(size=0.1) + 
  theme(axis.title.x=element_blank(), axis.title.y=element_blank())
ggsave('cust_TSNE_max.png', plot_TSNE_max, width = 6, height = 6)
print(plot_TSNE_max)
```

```{r Scores on gower cust TSNE}
dim_tab_names = c('Clusters', 'ARI', 'AMI', 'Sil')
g_tsne_evals = array(dim=c(2,4), dimnames = list(c(1:2), dim_tab_names))

dist_gower_tsne_cust <- dist(tsne_res$Y, method="euclidean")

g_tsne_evals[1,1] <- clusters_globalSEmax
g_tsne_evals[1,2] <- ARI(cust_clus, labels_globalSEmax)
g_tsne_evals[1,3] <- AMI(cust_clus, labels_globalSEmax)
g_tsne_evals[1,4] <- mean(silhouette(labels_globalSEmax, dist_gower_tsne_cust)[,3])

g_tsne_evals[2,1] <- clusters_globalmax
g_tsne_evals[2,2] <- ARI(cust_clus, labels_globalmax)
g_tsne_evals[2,3] <- AMI(cust_clus, labels_globalmax)
g_tsne_evals[2,4] <- mean(silhouette(labels_globalmax, dist_gower_tsne_cust)[,3])

print(kable(g_tsne_evals, caption = 'Clustering Statistics on TSNE Projections'))
```



```{r silhouette scores all}
dim_all_names = c('Clusters', 'MDS', 'FAMD', 'TSNE')
g_all_sils = array(dim=c(2,4), dimnames = list(c(1:2), dim_all_names))

g_all_sils[1,1] <- clusters_globalSEmax
g_all_sils[1,2] <- mean(silhouette(labels_globalSEmax, dist_gower_mds_cust)[,3])
g_all_sils[1,3] <- mean(silhouette(labels_globalSEmax, dist_gower_famd_cust)[,3])
g_all_sils[1,4] <- mean(silhouette(labels_globalSEmax, dist_gower_tsne_cust)[,3])

g_all_sils[2,1] <- clusters_globalmax
g_all_sils[2,2] <- mean(silhouette(labels_globalmax, dist_gower_mds_cust)[,3])
g_all_sils[2,3] <- mean(silhouette(labels_globalmax, dist_gower_famd_cust)[,3])
g_all_sils[2,4] <- mean(silhouette(labels_globalmax, dist_gower_tsne_cust)[,3])

print(kable(g_all_sils, caption = 'Silhouette Score on Different Projections'))
```

